server:
  port: 8081
  servlet:
    context-path: /itemservice
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: item_admin
    password: item_admin
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/