server:
  port: 8082
  servlet:
    context-path: /cartservice
spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: cart_admin
    password: cart_admin
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

