server:
  port: 8083
  servlet:
    context-path: /billingservice
spring:
  application:
    name: billing-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/